### ISSUE TITLE
[BUG]: MoreTags not displaying any tags

### ISSUE THREAD

**Issue by KarsonTheFoxx** [C10udburst/aliucord-plugins#24]
### Description of the bug

After the app crashed more tags has not been working since. 
Tried disabling and re-enabling it to completely re-installing the app

### Steps To Reproduce

1. Install plugin
2. Crash the app with another plugin
3.  Observe how the tags are no longer there

### Additional Information

![Screenshot_20221012_071353](https://user-images.githubusercontent.com/95767655/195361023-9e19f559-e686-4bd7-afeb-ec753b2d28ad.jpg)
![Screenshot_20221012_071514](https://user-images.githubusercontent.com/95767655/195361025-6e0fdc6e-e178-4a1e-b780-9611f0a6efbc.jpg)

**Comment by C10udburst** [comment]
ideally the other plugin shouldnt crash :trollface:

**Comment by C10udburst** [comment]
have you tried removing the json file which contains the settings?

**Comment by KarsonTheFoxx** [comment]
> 

I'm not sure how to do that

**Comment by C10udburst** [comment]
it should be sth like `/sdcard/Aliucord/settings/MoreTags.json` (or sth similar, i cant remember exactly)

**Comment by KarsonTheFoxx** [comment]
That would be assuming i have an SD card inserted. also i found it also mislabels some people as "webhooks" while not giving anyone else a tag

**Comment by C10udburst** [comment]
no, `/sdcard/` is your internal flash storage for some reason lol

**Comment by KarsonTheFoxx** [comment]
Mine is `/internal storage` `/SD card` gives me a message "SD card not inserted`

**Comment by KarsonTheFoxx** [comment]
Found it it was on this path `/internal storage/aliucord/settings/MoreTags.json`

**Comment by KarsonTheFoxx** [comment]
This has also fixed it, I think turning on "all roles" breaks it
