### ISSUE TITLE
[BUG]: Tags not appearing

### ISSUE THREAD

**Issue by the-da9l** [C10udburst/aliucord-plugins#25]
### Description of the bug

After the new username update, multiple users on the Aliucord discord as well as myself are experiencing that the plugin no longer works, and tags do not appear despite reinstall of the plugin. The client used is Aliucord.

### Steps To Reproduce

The tags don't work despite the plugin being enabled, out of the box.

**Comment by C10udburst** [comment]
Can't reproduce
