### ISSUE TITLE
[TextReplace]: feature request

### ISSUE THREAD

**Issue by OasisVee** [C10udburst/aliucord-plugins#26]
### Description

maybe a setting for rules where its exact case
ex: a rule that replaces b? with ૮꒰˶ᵔ ᵕ ᵔ˶ ꒱ა
without exact case if b? shows up at all it will replace it with ૮꒰˶ᵔ ᵕ ᵔ˶ ꒱ა
with exact case, if someone types something like "hey anyone see the new blob?" it won't replace it to make it appear like "hey anyone see the new blo૮꒰˶ᵔ ᵕ ᵔ˶ ꒱ა"

**Comment by C10udburst** [comment]
do regex rule with `^b\?$`, that will only match messages that are equal to b?
